apiVersion: v1
kind: ConfigMap
metadata:
  name: dcn-netbox-infra-check-config-{{ .Values.infrastructure }}
  namespace: dcn-checks
data:
{{- range $key, $val := .Values.data }}
  {{ $key }}: |
{{ $val | indent 4 }}
{{- end }}
