infrastructure: "prod"
image:
  repository: "ncr.sky.nhn.no/ghcr/norskhelsenett/dcn-netbox-infra-check"
  tag: "latest"
  pullPolicy: "Always"

schedule: "0 8 * * *"

data:
  config.json: |
    {
      "netbox_url": "https://ipam.dcn.nhn.no",
      "nam_url": "https://dcn.nhn.no:3000",
      "slack_webhook_url": "",
      "checks": [
        {
          "netbox_site_id": 715,
          "infra": "prod",
          "vdc_name": "nhn-trd2-vdc04"
        },
        {
          "netbox_site_id": 782,
          "infra": "prod",
          "vdc_name": "nhn-bgo1-vdc15"
        },
        {
          "NETBOX_SITE_ID": 714,
          "INFRA": "prod",
          "VDC_NAME": "nhn-trd1-vdc01"
        },
      ]
    }
