infrastructure: "prod"
namespace: "dcn-checks"
nameOverride: ""
image:
  repository: "ncr.sky.nhn.no/ghcr/norskhelsenett/dcn-netbox-infra-check"
  tag: "latest"
  pullPolicy: "Always"

successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 3

schedule: "0 6 * * *"

data:
  config.json: |
    {
      "netbox_url": "https://ipam.dcn.nhn.no",
      "nam_url": "https://dcn.nhn.no:3000",
      "esm_url": "https://esm.nhn.no",
      "esm_user": "sa-m2p-api-dcn-rw",
      "esm_tenant_id": 708190274,
      "esm_offering_id": "26390",
      "esm_requester_id": "250226",
      "esm_service_id": "188780",
      "esm_team_id": "18526",
      "slack_webhook_url": "",
      "checks": [
        {
          "netbox_site_id": 715,
          "infra": "prod",
          "vdc_name": "nhn-trd2-vdc04"
        },
        {
          "netbox_site_id": 782,
          "infra": "prod",
          "vdc_name": "nhn-bgo1-vdc15"
        },
        {
          "netbox_site_id": 714,
          "infra": "prod",
          "vdc_name": "nhn-trd1-vdc01"
        }
      ]
    }
