infrastructure: "qa"
namespace: "dcn-checks"

image:
  repository: "ncr.sky.nhn.no/ghcr/norskhelsenett/dcn-netbox-infra-check"
  tag: "latest"
  pullPolicy: "Always"

successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 3

schedule: "0 8 * * *"

data:
  config.json: |
    {
      "netbox_url": "https://ipam.qa.dcn.nhn.no",
      "nam_url": "https://qa.dcn.nhn.no:3000",
      "esm_url": "https://test.esm.nhn.no",
      "esm_user": "sa-m2t-api-dcn-rw",
      "esm_tenant_id": 938019087,
      "esm_offiring": "68905",
      "esm_requester_id": "200198",
      "slack_webhook_url": "",
      "checks": [
        {
          "netbox_site_id": 715,
          "infra": "prod",
          "vdc_name": "nhn-trd2-vdc04"
        },
        {
          "netbox_site_id": 782,
          "infra": "prod",
          "vdc_name": "nhn-bgo1-vdc15"
        },
        {
          "NETBOX_SITE_ID": 714,
          "INFRA": "prod",
          "VDC_NAME": "nhn-trd1-vdc01"
        }
      ]
    }
