apiVersion: v1
kind: ConfigMap
metadata:
  name: dcn-netbox-infra-check-config
  namespace: dcn-checks
data:
  config.json: |
    {
      "netbox_url": "https://ipam.dcn.nhn.no",
      "nam_url": "https://dcn.nhn.no:3000",
      "slack_webhook_url": ""
      "checks": [
        {
          "netbox_site_id": 715,
          "infra": "prod",
          "vdc_name": "nhn-trd2-vdc04"
        },
        {
          "netbox_site_id": 782,
          "infra": "prod",
          "vdc_name": "nhn-bgo1-vdc15"
        }
      ]
    }
