apiVersion: v1
kind: Secret
metadata:
  name: dcn-netbox-infra-check-secrets
  namespace: dcn-checks
type: Opaque
stringData:
  netbox-token: "your-netbox-api-token-here"
  nam-token: "your-nam-api-token-here"
  esm-password: "your-esm-password-here"
